image: docker:19.03.1
services:
  - docker:19.03.1-dind

stages:
  # - build
  - test
  # - release
  # - deploy

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REwwwwwwwGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# build:
#   stage: build
#   script:
#     - docker build --pull -t $CONTAINER_TEST_IMAGE .
#     - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  variables:
    # GOSS_FILES_PATH: .misc/goss
    GOSS_FILES_STRATEGY: cp
  before_script:
    - apk add --update curl
    - curl -fsSL https://goss.rocks/install | sh
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - export GOSS_FILES_STRATEGY=cp
    - ls -la /goss
    - dgoss run -it $CONTAINER_TEST_IMAGE

# release-image:
#   stage: release
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#     - docker push $CONTAINER_RELEASE_IMAGE
#   only:
#     - master

# deploy:
#   stage: deploy
#   script:
#     - ./deploy.sh
#   only:
#     - master